[package]
name = "EMBER"
version = "0.1.0"
edition = "2021"



[dependencies]
ash = { version = "0.38.0", features = ["linked"] }
winit = "0.30.9"
ash-window = "0.13.0"

windows = { version = "0.61.1", features = ["Win32_Graphics_Dwm", "Win32_Graphics_Gdi"] }
libloading = "0.8.6"